/**
 * @file main.c
 * @brief Main application entry point with auto-generated initialization sequence
 *
 * This file was auto-generated by the BSP Generator.
 * Initialization order is based on dependency analysis.
 */

#include <stdint.h>
#include <stddef.h>

// Module headers
#include "system.h"
#include "pll_driver.h"
#include "vim.h"
#include "pcr_driver.h"
#include "iomm_driver.h"
#include "lin_driver.h"
#include "gio_driver.h"
#include "sci_driver.h"

/**
 * @brief Main application entry point
 *
 * Initializes all BSP modules in dependency order:
 * 1. SYSTEM (dependencies: none)
 * 2. PLL (dependencies: SYSTEM)
 * 3. VIM (dependencies: SYSTEM)
 * 4. PCR (dependencies: PLL)
 * 5. IOMM (dependencies: PLL)
 * 6. LIN (dependencies: VIM, PLL, IOMM)
 * 7. GIO (dependencies: VIM, PLL, IOMM)
 * 8. SCI (dependencies: VIM, PLL, IOMM)
 *
 * @return Never returns (infinite loop)
 */
int main(void)
{
    /* ===== BSP Initialization Sequence ===== */
    /* Auto-generated based on dependency analysis */

    /* Initialize SYSTEM (no dependencies) */
    system_init();

    /* Initialize PLL (depends on: SYSTEM) */
    PLL_Init();

    /* Initialize VIM (depends on: SYSTEM) */
    vim_init();

    /* Initialize PCR (depends on: PLL) */
    PCR_Init();

    /* Initialize IOMM (depends on: PLL) */
    IOMM_Init();

    /* Initialize LIN (depends on: VIM, PLL, IOMM) */
    LIN_Init();

    /* Initialize GIO (depends on: VIM, PLL, IOMM) */
    GIO_Init();

    /* Initialize SCI (depends on: VIM, PLL, IOMM) */
    SCI_Init();

    /* ===== Application Code ===== */
    /* TODO: Add your application logic here */

    /* Main loop */
    while (1)
    {
        /* Application main loop */
        /* TODO: Add periodic tasks, event handling, etc. */
    }

    return 0; /* Never reached */
}
