[project]
name = "bsp-generator"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "boto3>=1.40.50",
    "chromadb>=1.1.1",
    "langchain>=0.3.27",
    "langchain-aws>=0.2.35",
    "langchain-community>=0.3.31",
    "pdfplumber>=0.11.7",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
    "types-boto3[full]>=1.40.51",
]

[tool.ruff.lint]
ignore = ["E402"]  # Allow imports after code
