/* BSP-GEN-META: created_at=2026-03-04T23:27:23-08:00; output_folder=output_20260304_232329; output_tag=20260304_232329 */
/**
 * @file main.c
 * @brief Main application entry point with auto-generated initialization sequence
 *
 * This file was auto-generated by the BSP Generator.
 * Initialization order is based on dependency analysis.
 */

#include <stdint.h>
#include <stddef.h>

// Module headers
#include "system.h"
#include "pcr_driver.h"
#include "iomm_driver.h"
#include "pll_driver.h"
#include "vim_driver.h"
#include "sci_driver.h"
#include "lin_driver.h"
#include "gio_driver.h"
#include "app_intent.h"

/**
 * @brief Main application entry point
 *
 * Initializes all BSP modules in dependency order:
 * 1. SYSTEM (dependencies: none)
 * 2. PCR (dependencies: none)
 * 3. IOMM (dependencies: none)
 * 4. PLL (dependencies: SYSTEM)
 * 5. VIM (dependencies: SYSTEM)
 * 6. SCI (dependencies: PLL, IOMM)
 * 7. LIN (dependencies: VIM, PLL, IOMM)
 * 8. GIO (dependencies: VIM, IOMM)
 *
 * @return Never returns (infinite loop)
 */
int main(void)
{
    /* ===== BSP Initialization Sequence ===== */
    /* Auto-generated based on dependency analysis */

    /* Initialize SYSTEM (no dependencies) */
    system_init();

    /* Initialize PCR (no dependencies) */
    PCR_Init();

    /* Initialize IOMM (no dependencies) */
    IOMM_Init();

    /* Initialize PLL (depends on: SYSTEM) */
    PLL_Init();

    /* Initialize VIM (depends on: SYSTEM) */
    vim_init();

    /* Initialize SCI (depends on: PLL, IOMM) */
    /* TODO: Uncomment to enable SCI */
    /* SCI_Init(); */

    /* Initialize LIN (depends on: VIM, PLL, IOMM) */
    /* TODO: Uncomment to enable LIN */
    /* LIN_Init(); */

    /* Initialize GIO (depends on: VIM, IOMM) */
    /* TODO: Uncomment to enable GIO */
    /* GIO_Init(); */

    /* ===== Application Code ===== */
    /* TODO: Add your application logic here */

    /* Main loop */
    APP_INTENT_Init();

    while (1)
    {
        APP_INTENT_Step();
        /* Application main loop */
        /* TODO: Add periodic tasks, event handling, etc. */
    }

    return 0; /* Never reached */
}
